### ISSUE TITLE
[request] support custom FarmType File_Conditions

### ISSUE THREAD

**Issue by nephatrine** [Esca-MMC/FarmTypeManager#17]
It looks like the FarmTypes enum only covers the normal farm types and there isn't a way to specify a condition such that only additional farm types would be handled. For instance, when using MTN whichFarm can produce values > 4. It would be nice to be able to specify a catch-all like "FarmTypes": ["Custom"] to cover all such non-vanilla farms or even allow the numeric index to be directly input so a user could make the rule specific to a single MTN-added farm layout.

**Comment by Esca-MMC** [comment]
Good suggestion, it's an issue I'd put off in earlier versions.

Commit 54a9aa1 adds support for integers (whichFarm values) in the FarmTypes condition list, e.g. `["Standard", "Forest", 5, 177]`. In MTN content packs, that will be the "ID" setting in the pack's farmTypes.json file.

Custom farm type name recognition isn't supported for now, since it would require direct support and might be rewritten when SDV 1.4 is released. (SDV itself doesn't explicitly track the farm type's name within its own code.)
