### ISSUE TITLE
"Dark Sword" causes the save to be unresponsive for a long time

### ISSUE THREAD

**Issue by Jumping-notes** [Esca-MMC/FarmTypeManager#26]
I'm not sure if there is a compatibility issue with Margo, But the Dark Sword does belong to Margo,which causes long periods of unresponsiveness during overnight saves
https://smapi.io/log/0db1342ec32f419882701228afbdf7b0

**Comment by Esca-MMC** [comment]
That message is unrelated to the delay. Farm Type Manager is only active for 1 second (09:31:56 - 09:31:57) overnight in that log. Enable the "Trace" messages for more detail.

The largest delay (about 4 minutes) appears on this line, where SMAPI needs to reload 92 game files because they were edited by various mods:
`09:31:56   TRACE SMAPI   Invalidated 92 asset names [...]`

Unfortunately, I don't have any advice about how to improve that.
